server:
  port: 3344

spring:
  application:
    #注册到Eureka服务中心的微服务名
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangshuai2732/springcloud-config.git
          search-paths:
            #github上项目名
            - springcloud-config
      #读取分支
      label: master

#注册到eureka的服务地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

