server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
          enabled: true
      routes:
        #路由的id,没有规定规则但要求唯一,建议配合服务名
        - id: payment_route
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          #断言，路径相匹配的进行路由 ,http://localhost:9527/payment/get/**
                                #-->http://localhost:8001/payment/get/**
          predicates:
            - Path=/payment/get/**

        #路由的id,没有规定规则但要求唯一,建议配合服务名
        - id: payment_route2
          #匹配后提供服务的路由地址
          uri: http://news.baidu.com
          predicates:
            - Path=/guonei

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/