server:
  port: 80
eureka:
  client:
    register-with-eureka: true #服务注册到eureka，默认就是true
    fetch-registry: true   #是否从EurekaServer抓取已有的注册信息，默认为true。提供者使用该属性才能负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka
     #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#ribbon:
#  #建立连接后从服务器读取到可用资源所用的事件
#  ReadTimeout: 5000
#  #两端连接所用的事件
#  ConnectTimeout: 5000

#feign日志以什么级别监控哪个接口
logging:
  level:
    com.combat.cloud.service.PaymentFeignService:
      debug

feign:
  #开启feign的hystrix功能，在注解@FeignClient中添加fallbackFactory
  hystrix:
    enabled: true
