server:
  #8004表示注册到zookeeper服务器的支付服务提供者端口号
  port: 8004
spring:
  application:
    #服务名---注册zookeeper到注册中心的名称
    name: cloud-provider-payment
  cloud:
    zookeeper:
      #zookeeper运行的ip地址:clientPort2181
      connect-string: 192.168.184.130:2181